#!/bin/bash

# SSH Port Configuration for Borg Operations
# Run this script on SARK (192.168.68.69) with sudo privileges

echo "SSH Port Configuration Script"
echo "=============================="
echo ""
echo "This script will configure SSH to listen on both ports 22 and 2222"
echo "Required: Run with sudo privileges"
echo ""
echo "Commands to run manually:"
echo ""
echo "1. Backup current SSH config:"
echo "   sudo cp /etc/ssh/sshd_config /etc/ssh/sshd_config.backup.\$(date +%Y%m%d_%H%M%S)"
echo ""
echo "2. Add port 2222 to SSH config:"
echo "   sudo sed -i '/^Port 22$/a Port 2222' /etc/ssh/sshd_config"
echo ""
echo "3. Restart SSH service:"
echo "   sudo systemctl restart sshd"
echo ""
echo "4. Verify SSH is listening on both ports:"
echo "   sudo netstat -tlnp | grep ':22.*LISTEN'"
echo "   sudo netstat -tlnp | grep ':2222.*LISTEN'"
echo ""
echo "5. Test SSH connection to port 2222:"
echo "   ssh -p 2222 maxvamp@192.168.68.69 'echo \"SSH connection successful\"'"
echo ""
echo "6. Enable SSH to start on boot:"
echo "   sudo systemctl enable sshd"
echo ""
echo "After running these commands, Vorta should be able to connect"
echo "to 192.168.68.69:2222 for Borg operations."